# Generated by Django 5.0.1 on 2024-01-06 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Title", models.CharField(max_length=20, null=True)),
                ("Description", models.CharField(max_length=20, null=True)),
                ("Created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "User",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.account"
                    ),
                ),
            ],
        ),
    ]
