# Generated by Django 5.0.1 on 2024-01-08 21:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_post"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="User",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="app.account"
            ),
        ),
    ]
