# Generated by Django 5.0 on 2023-12-14 21:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_account_delete_customer"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="password",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="account",
            name="password2",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="account",
            name="Phone_Number",
            field=models.IntegerField(null=True),
        ),
    ]
