# Generated by Django 5.0 on 2023-12-15 20:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0004_account_password_account_password2_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="account",
            name="password2",
        ),
    ]
