# Generated by Django 5.0.1 on 2024-01-09 17:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0004_alter_post_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="Description",
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="Title",
            field=models.CharField(max_length=60, null=True),
        ),
    ]
