# Generated by Django 5.0.1 on 2024-01-09 17:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0005_alter_post_description_alter_post_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="Description",
            field=models.CharField(max_length=3000, null=True),
        ),
    ]
