# Generated by Django 5.0 on 2023-12-15 21:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0005_remove_account_password2"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="account",
            name="Phone_Number",
        ),
    ]
