# Generated by Django 5.0.1 on 2024-01-09 17:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0006_alter_post_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="Image",
            field=models.ImageField(blank=True, null=True, upload_to="post_images/"),
        ),
    ]
