# Generated by Django 5.0.1 on 2024-01-10 16:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0007_post_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="ProfilePic",
            field=models.ImageField(blank=True, null=True, upload_to="post_images/"),
        ),
    ]
