# Generated by Django 5.0.1 on 2024-01-10 16:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0009_remove_account_profilepic_userpic"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserPic",
        ),
    ]
