# Generated by Django 5.0.1 on 2024-01-10 16:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0010_delete_userpic"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="UserPic",
            field=models.ImageField(blank=True, null=True, upload_to="post_images/"),
        ),
    ]
